// <auto-generated />
using MTG295NTermProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTG295NTermProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313034324_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MTG295NTermProject.Models.CardModel", b =>
                {
                    b.Property<int>("CardModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CardModelId"));

                    b.Property<int>("CardColor")
                        .HasColumnType("int");

                    b.Property<string>("CardColor2")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor3")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor4")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor5")
                        .HasColumnType("longtext");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CardType")
                        .HasColumnType("int");

                    b.Property<string>("CardType2")
                        .HasColumnType("longtext");

                    b.Property<string>("CardType3")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType2")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType3")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType4")
                        .HasColumnType("longtext");

                    b.Property<string>("Kindred")
                        .HasColumnType("longtext");

                    b.Property<string>("Legendary")
                        .HasColumnType("longtext");

                    b.Property<int>("ManaCost")
                        .HasColumnType("int");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Power")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Toughness")
                        .HasColumnType("longtext");

                    b.HasKey("CardModelId");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
