// <auto-generated />
using MTG295NTermProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTG295NTermProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MTG295NTermProject.Models.CardModel", b =>
                {
                    b.Property<int>("CardModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CardColor")
                        .HasColumnType("int");

                    b.Property<string>("CardColor2")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor3")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor4")
                        .HasColumnType("longtext");

                    b.Property<string>("CardColor5")
                        .HasColumnType("longtext");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CardType")
                        .HasColumnType("int");

                    b.Property<string>("CardType2")
                        .HasColumnType("longtext");

                    b.Property<string>("CardType3")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType2")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType3")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatureType4")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Kindred")
                        .HasColumnType("longtext");

                    b.Property<string>("Legendary")
                        .HasColumnType("longtext");

                    b.Property<int>("ManaCost")
                        .HasColumnType("int");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Power")
                        .HasColumnType("longtext");

                    b.Property<double?>("PriceUSD")
                        .HasColumnType("double");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Toughness")
                        .HasColumnType("longtext");

                    b.HasKey("CardModelId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTG295NTermProject.Models.WantedCardModel", b =>
                {
                    b.Property<string>("CardName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CardName");

                    b.ToTable("WantedCards");
                });
#pragma warning restore 612, 618
        }
    }
}
